---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# These tests are meant to be run by another Ansible (i.e, the one built with build-single-release.yaml)
- name: Run nested Ansible tests
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Use community.general.binary_file lookup
      ansible.builtin.assert:
        that:
          - query("community.general.binary_file", playbook_dir ~ "/nested-ansible-tests.yaml")[0]
            ==
            query("ansible.builtin.file", playbook_dir ~ "/nested-ansible-tests.yaml", rstrip=false)[0] | b64encode

    - name: Use community.docker.current_container_facts
      community.docker.current_container_facts:

    - name: Use community.dns.reverse_pointer filter
      ansible.builtin.assert:
        that:
          - >-
            "192.168.1.1" | community.dns.reverse_pointer == "1.1.168.192.in-addr.arpa."
